import Head from 'next/head';
import { ReactNode } from 'react';

type pageLayoutProps = {
  children: ReactNode;
  title: string;
};

export function PageLayout({ children, title }: pageLayoutProps) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
      <footer>footer</footer>
    </>
  );
}
